### ISSUE TITLE
It seems that, caches can not cache count result

### ISSUE THREAD

**Issue by meixiaofei** [go-gorm/caches#2] opened 2023-07-27 11:14 UTC
only works with fetch rows

Good example:
```go
var list []Item
db.find(&list)
```

Bad example:
```go
var count int64
db.count(&count)
```

The reason count doesn't work might be related to this:
https://github.com/go-gorm/gorm/blob/a7f01bd1b22ec7131c420de62abe5f7e85573277/finisher_api.go#L490-L495

**Comment by ktsivkov** [comment] 2023-08-04 16:49
Hello @meixiaofei , seems like the issue is because the caches plugin stores the value as a pointer to an int64. Will check what I can do to fix it.

**Comment by ktsivkov** [comment] 2023-08-04 21:15
Hey @meixiaofei please check - https://github.com/go-gorm/caches/pull/3 if it is working I can merge and release a new major version since it breaks the Cacher interface api.

**Comment by meixiaofei** [comment] 2023-08-05 13:58
> Hey @meixiaofei please check - #3 if it is working I can merge and release a new major version since it breaks the Cacher interface api.

It's working now. I also tried the Easer option, and it works well too, Great job<g-emoji alias="heart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2764.png" class="social-button-emoji">❤️</g-emoji>. @ktsivkov

**Comment by ktsivkov** [comment] 2023-08-05 14:02
@meixiaofei perfect! I am closing the issue and releasing version 2.0.0 of this plugin!

**Closed by ktsivkov** 2023-08-05 14:02 UTC
